### ISSUE TITLE
Test Properly in CI workflows

### ISSUE THREAD

**Issue by Shredmetal** [Shredmetal/llmtest#16]
### 1. Test Core Functionality in CI
- [x] Test with GitHub Actions

### 2. Document CI Integration
- [x] GitHub Actions example
- [x] Environment variable setup guide
- [x] Best practices for CI integration

### 3. Test Common Scenarios - run the whole range of tests in library in CI
- [x] Basic semantic assertions
- [x] Complex test cases
- [x] Rate limiting behavior
- [x] Error handling
- [x] Configuration management

### 4. Create Example Workflows for GitHub Actions
- [x] Basic workflow example

## Success Criteria
1. Library functions correctly in GitHub Actions
2. Documentation provides clear integration guides
3. Example workflows are verified and documented
4. Environment variable handling is reliable

**Comment by Shredmetal** [comment]
I am super in over my head here, if anybody wants to contribute, please let me know!

**Comment by eLn86** [comment]
This is resolved with the very recent addition of rate limiter behavior tests
